spring.application.name=HRPlus


spring.datasource.url=jdbc:mysql://localhost:3306/HRPlus
spring.datasource.username=root
spring.datasource.password=Rajesh@8875

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080


spring.security.user.name=raja
spring.security.user.password=Rajesh